### ISSUE TITLE
Allow multiple NATS servers

### ISSUE THREAD

**Issue by rickfarmer** [pivotal-cf/cf-rabbitmq-release#11]
Currently, only one NATS server can be entered into the RabbitMQ manifest under the global properties for the broker.
Ideally an array would be allowed for an entry here.  Having tried entering an array, it will not take it since the release does not appear to allow for it.

**Comment by avade** [comment]
Thanks Rick for highlighting this Rick. You are right currently only one NATS server can be specified.

We are waiting for the [CF Routing API](https://docs.google.com/document/d/1iSrqmjRDEM0y_nIgk-iXNR9P-ODV7E-StN4UMj8y0lQ/edit#heading=h.4k2cr6pdcze8) to become available, then we expect to switch the BOSH release to this instead of going directly to NATS.

If you want to submit a PR for this feature then we can consdier merging it.
