### ISSUE TITLE
inconsistencies with tags

### ISSUE THREAD

**Issue by nbari** [pivotal-cf/cf-rabbitmq-release#239]
What is the logic behind committing new releases with random order regarding the tag versions?

For example, days ago there was a commit with the tag `v270.0.0` and now the latest commit has lower "version" `v267.3.0`. Based on time one may assume (has listed also here: https://github.com/pivotal-cf/cf-rabbitmq-release/releases looks like the latest stable is `v267.3.0` but then what is the point of `v270.0.0`

Probably would be better to have different branches for "possible test" but in any case, I would highly suggest to please  keep a healthy sequence in the tags

**Comment by MirahImage** [comment]
Hi, our pipeline ran into some issues recently when we started automating our release process, releasing with every successful build. While some of the problems are due to fundamental structural problems that we have not yet found a way to overcome, we've hopefully fixed the most recent releases. Our apologies for the issue, it impacted us as well.
