### ISSUE TITLE
Regression: deleting broker user on startup bricks running Java applications

### ISSUE THREAD

**Issue by ae-govau** [pivotal-cf/cf-rabbitmq-release#395]
Commit 4614f7b8fb73af9123505c92133926640b96749e changes `post-start` to always delete the `broker` user before adding it again.

This breaks any running applications that connect to the Rabbit after it starts, but before `post-start` is run. Worse, the authentication failure is regarded as `FATAL` by the Java Spring `SimpleMessageListenerContainer`, meaning that the result of an authentication failure is the the `SimpleMessageListenerContainer` will abort the consumer and not re-try to connect (as it normally would if the Rabbit were simply down).

Worse, when a `SimpleMessageListenerContainer` consumer aborts, this doesn't (by default) trigger the Java application to stop, so CloudFoundry will continue to think that is healthy, even though it's primary purpose has ceased, leaving the app essentially bricked requiring manual intervention to restart.

While there's not much you can do about that in the RabbitMQ release, it would be helpful to stop deleting a user upon each restart / stemcell roll as this will break running applications. This feels like a recent regression that I think started with that commit.

There are a number of other approaches that spring to mind:

1. Don't listen on correct port until all initialisation is complete.
2. Don't delete a user if that user/credential combination is still valid.
3. There may be other better options.

**Comment by ansd** [comment]
Thanks @ae-govau for describing this issue so accurately.

We didn't notice this regression since we use that broker admin user only in our [on-demand service broker](https://github.com/pivotal-cf/on-demand-service-broker) where the broker admin user is not used in RabbitMQ client apps but is used to create and delete other RabbitMQ users (during binding and unbinding) which are in turn used in client apps.

https://github.com/pivotal-cf/cf-rabbitmq-release/pull/402 solves your issue by implementing the 2nd approach you suggested. Feel free to test that PR.

**Comment by ae-govau** [comment]
Looks good to me, thanks @ansd.  We don't have a pipeline set up to easily the build, but the approach looks fine.
