### ISSUE TITLE
Releases are no longer published on bosh.io

### ISSUE THREAD

**Issue by bg-govau** [pivotal-cf/cf-rabbitmq-release#408]
We have noticed that new releases are no longer being published to https://bosh.io/releases/github.com/pivotal-cf/cf-rabbitmq-release - the last one at the moment is 336.0.0. Is this intentional, or something that can be fixed?

**Comment by ferozjilla** [comment]
Hi @bg-govau, thanks for bringing this up!

This is not intentional, and is an unintended side effect of changing our release process to push final releases on a `release` branch instead of the former `master` branch.

We have a story in our backlog to fix this shortly :)

**Comment by thomasmitchell** [comment]
@ferozjilla any updates on this?

**Comment by jimconner** [comment]
It would be really good if the releases could start flowing to bosh.io again.... Please... Pretty Please :-)

**Comment by combor** [comment]
_We have a story in our backlog to fix this shortly :)_  How long is your backlog ?

**Comment by pousa** [comment]
Any updates on this? ;)

**Comment by 9numbernine9** [comment]
It looks like they're being published again!  🎉 
https://bosh.io/releases/github.com/pivotal-cf/cf-rabbitmq-release?version=389.0.0

**Comment by mymasse** [comment]
Hopefully the same thing will happen to the `cf-rabbitmq-smoke-tests` and `cf-rabbitmq-multitenant-broker` releases, cause they are still not published on bosh.io

**Comment by ansd** [comment]
Sorry you had to wait for 10 months.

We now changed the default branch of repos

- https://github.com/pivotal-cf/cf-rabbitmq-release
- https://github.com/pivotal-cf/cf-rabbitmq-smoke-tests-release
- https://github.com/pivotal-cf/cf-rabbitmq-multitenant-broker-release

to be the `release` branch because
>bosh.io does not pay attention to GitHub releases. It watches the releases directory within your GitHub repository on the default branch, which contains the metadata for final releases.

https://github.com/bosh-io/releases#how-does-boshio-find-my-release

All dev commits and PRs will continue to go against `master` branch.
