### ISSUE TITLE
Reason to use IP address md5 as node name

### ISSUE THREAD

**Issue by MatthiasWinzeler** [pivotal-cf/cf-rabbitmq-release#56]
We were wondering why `cf-rabbitmq-release` [uses the ip address of the node as its RMQ node name (in setup.sh)](https://github.com/pivotal-cf/cf-rabbitmq-release/blob/9654cae8c98a53eefa881196e7504fbfcb39f902/jobs/rabbitmq-server/templates/setup.sh.erb#L129).

RMQ seems to rely on this node name in different cases. So coupling the cluster to fixed IPs has some drawbacks:

- Because it seems to confuse the cluster when the node name changes, it makes it impossible to use dynamic IPs for the nodes or change static IPs after the first deployment
- If we'd like to migrate all data from one cluster to another with different IPs (i.e. in the migration case) by exporting the mnesia database, we can not do so since the mnesia database is bound to the node name and restore to a different node name is not supported according to Pivotal support.

Side note: We're aware that we can backup and restore the configuration using the `/api/definitions` endpoint, but this does not include the queue data.

Could the node name be changed to use another unique attribute of the node as the node name, i.e. `job_name/job_index`? This would still be unique but would decouple the cluster from the used IPs, i.e allow us to move the deployment around.

**Comment by michaelklishin** [comment]
@MatthiasWinzeler `job_name/job_index` isn't a unique attribute when multiple OpsMan Availability Zones are used. IIRC that's what this BOSH release used originally.

**Comment by MatthiasWinzeler** [comment]
OK. What would you think about adding this as an option?
I.e. introduce something like `use_job_names_as_node_names`?

**Comment by michaelklishin** [comment]
@MatthiasWinzeler I no longer maintain this project. Someone from the team that does will get back to you :)

**Comment by davidhiston** [comment]
@MatthiasWinzeler Thanks for the suggestion.  This is something that we are planning on doing in the future for the reasons which you mention above.

**Comment by gerhard** [comment]
Thank you @MatthiasWinzeler for validating our assumption that we definitely need to address this. I expect the bulk of the work to be in migrating existing deployments, which already use MD5 IPs for nodenames.

Availability Zones support has come a long way in recent years, [BOSH now supports multiple AZs natively](https://bosh.io/docs/azs.html).

The nodename that makes most sense is `rabbit@<%= "#{spec.name}#{spec.index}-#{spec.deployment}`. Notice that I am not using `.` anywhere in the nodename, otherwise we would need to deal with FQDNs and long nodenames. We use the deployment name to makes it easier to cluster nodes across multiple deployments. A deployment name also makes it more convenient when collecting metrics.

cc @totherme @BenChapman

**Comment by BenChapman** [comment]
Hi,

As @davidhiston has said, we have plans to work on this in the future but as there's nothing immediately addressable we'll close this issue for now.

Thanks,
@benchapman & @dlresende
