### ISSUE TITLE
Where is the cf-rabbitmq-multitenant-broker release?

### ISSUE THREAD

**Issue by grenzr** [pivotal-cf/cf-rabbitmq-release#59]
I see it referenced in the README (https://github.com/pivotal-cf/cf-rabbitmq-broker-release which gives a 404) and in https://github.com/pivotal-cf/cf-rabbitmq-release/blob/master/manifests/cf-rabbitmq-colocated-with-multitenant-broker-template.yml.

Are there plans to make it public or do we need to package our own?

**Comment by vlad-stoian** [comment]
Hi @grenzr, 
Thanks for raising this problem. We're planning to make the multitenant broker repo public, although I cannot give an estimate on when at this point.

We'll get back to you and let you know once that happens.

**Comment by mymasse** [comment]
It's been a month since the last comment, any idea when it will be available? Kind of frustrating that something that was available before is suddenly not anymore.

**Comment by dlresende** [comment]
Hi @mymasse, we understand :(
What happened is that we refactored the multitenant-broker out of the rabbitmq bosh release. And when we create new repos they are private by default. In order to open source a private repo, Legal needs to get involved and that can take some extra time.
Right now Legal is in the process of reviewing everything. Hopefully it will be sorted out soon.

**Comment by hoegaarden** [comment]
Hi @grenzr and @mymasse, we've just open sourced the multitenant-broker-release repo. 

It's available at https://github.com/pivotal-cf/cf-rabbitmq-multitenant-broker-release

Thanks,
@hoegaarden and @albertoleal
