### ISSUE TITLE
Remove base64 decoding/encoding of rabbitmq-server.conf for bosh cli v2 compat

### ISSUE THREAD

**Issue by MatthiasWinzeler** [pivotal-cf/cf-rabbitmq-release#63]
Hi guys

The property [`rabbitmq-server.config`](https://github.com/pivotal-cf/cf-rabbitmq-release/blob/v229.2.0/jobs/rabbitmq-server/spec#L51) allows specifying additional rabbitmq server config. 

Currently, it expects a base64 encoded string as described in the [docs](https://github.com/pivotal-cf/cf-rabbitmq-release/blob/v229.2.0/docs/bosh_rabbitmq.md#unclustered-rabbit-with-customised-configuration).

However, this relies on the bosh cli to interpret ERB expressions in the deployment manifest. This was the case for the old ruby cli, but the new golang cli (v2) does (intentionally) not support this:
https://github.com/cloudfoundry/bosh-cli/issues/282

This forces bosh cli v2 users of this release to somehow (manually) preprocess the bosh deployment manifest before deploying (or just put base64 in the deployment manifest - either of it is not that nice) - it would be nicer if we could put the config as plain string, i.e. `rabbitmq-server.raw_config` or similar...  Would this be possible?

I can't see why passing `rabbitmq-server.config` as a plain string could lead to issues, i.e.:

```
rabbitmq-server:
  config: | 
    [{rabbit, [{vm_memory_high_watermark,0.5}]}].
```

**Comment by BenChapman** [comment]
Hi @MatthiasWinzeler,

Thanks for your issue. We now recommend generating the Base64 encoded value outside of the BOSH interpolation process, rather than using ERB to generate it inline in the manifest.

Due to other dependencies we cannot change the way the release handles this input, and we also cannot add another property that could configure this at the moment.

Thanks,
@benchapman & @dlresende
