### ISSUE TITLE
HIPE support

### ISSUE THREAD

**Issue by scottschulthess** [pivotal-cf/cf-rabbitmq-release#68]
Hey ya'll, one of the other rabbitmq https://github.com/rabbitmq/rabbitmq-server-boshrelease/blob/master/jobs/rabbitmq-server/spec#L141 supports "HIPE" (high performance erlang) that I was interested in playing around with, is this something that would be desirable to add to this bosh release? edit: Just realized/remember that the other boshrelease is experimental

**Comment by michaelklishin** [comment]
When HiPE is enabled, there is a 2-3 minute startup penalty unless a [pre-compiled directory is provided](https://github.com/rabbitmq/rabbitmq-server/pull/808). BOSH and monitoring systems may or may not be prepared for this. So this is not a matter of exposing a configuration key to the BOSH manifest. It has to be a feature that's covered at the pre-compilation stage.

**Comment by scottschulthess** [comment]
Closing for now then as this appears to be a feature request that would require more thught

**Comment by gerhard** [comment]
I believe that this BOSH release already supports it.

AFAIK, the Erlang package has hipe enabled - @scottschulthess do you want to validate this? - and the rabbitmq-server job exposes the `rabbitmq-server.config` property, so it's just a matter of setting it to a base64 encoded value of:

```erl
[
  {rabbit, [
    {hipe_compile, true}
  ]}
].
```

**Comment by gerhard** [comment]
A RabbitMQ 3.7.3 with all plugins enabled running on Erlang 20.2.2 & [n1-highmem-4](https://cloud.google.com/compute/pricing) takes 60s to compile:

```
2018-02-06 17:57:30.406 [info] <0.5.0> HiPE in use: compiled 57 modules in 60s.
```

BOSH handles this compilation penalty well, because the contract with the rabbitmq-server job is a PID file. As long as there is a process running with the PID that Monit tracks via this PID file, BOSH is oblivious to the fact that RabbitMQ is HiPE compiling.

I encourage you to try this feature, in either BOSH release. I have just confirmed that it works as advertised in rabbitmq-server-boshrelease, I can't foresee any issues in cf-rabbitmq-release provided you follow my previous instructions 🙂
